# print(2/3)
# print("{0:.5} , {1:.3}".format(4/3, 2/3))
# print("{0:*^11} , {1:╫^9}".format('hello', 'O'))
# print('backk\bspace')
# print('tab\ttab')
# print('new\nline')
# print('vertical\vtab')

products = input('Xarid qilmoqchi bo\'lgan mahsulotlaringizni kiriting\n>>>')
print('{0:-^41}'.format('shaxsiy xaridlar ro’yxati'))
print(products)